language: java
deploy:
  provider: heroku
  app: heroku-run
  api_key:
    secure: grpf+Tzlje3+MQ6gCkFVwvH0xxNMkhx66p4+IPXQICycatHfDHGIEJkUrN6L5pww+F9qEi42yBli1AEWZ0IgWEhesxkF2Da9cL8EHLzqQTwDvWkSl4qY1WXzqgCOCxpJp2s0+Uw8eMqUkPel198qUnEqBdAl4BTl8SIt1vBVmylDLxUZLpi86Bf7pP+95NsVflAjX+kdaKePHfd9Rz4V86qSP7MiSCGMfgr50KPd/u6tEMxhaz8azhlqbDALUpL+ggeBibtviPxErIR4wUfYjWo9vKdKn5jPaNZ/UtkG5yjwJr0rORPZdGO1tLhNPi7FHMLaAsYV8/iKIF4mjc0BloNMwGcw5jvbHiF/Qe8IzzgFYsl59VMXNoTONiJv3PtH7ul+K//Nl7x2+hdVeJ/jCL3NBS5pwz1IiDNn/APr0kxu2o455zo60J66efLs4qPiJLzuK18vXxYFIwZS/SiEZy4zdAI10SJlDzZ0/M5QLta8+Wu8p19Rh8bACgbKDLVt3G68KemQJzFnLdNfHHhdxeYgOtF/RWkOX8k0J22uP3HbdsS6MBV1OIvZOz+HxCMijlKJmTTHgTeX42Rl1kwB/s8AVeXpo5DCXGlJ2FRbk8PdwxzXK+PuY//JVA1v1+6jNq/Zu4pQoL26dYSRt6KmaIk61qna/c1myk7ryDIjwAc=
